import { Console } from "@nsnanocat/util";
import { normalizeLanguage } from "./language.mjs";

function getBaseUrlParameter(baseUrl, key) {
	if (!baseUrl) return undefined;
	try {
		return new URL(baseUrl).searchParams.get(key) ?? undefined;
	} catch {
		const match = String(baseUrl).match(new RegExp(`[?&]${key}=([^&]+)`, "i"));
		if (!match?.[1]) return undefined;
		try {
			return decodeURIComponent(match[1]);
		} catch {
			return match[1];
		}
	}
}

function getTrackLanguage(track) {
	return track?.languageCode ?? getBaseUrlParameter(track?.baseUrl, "lang") ?? "";
}

function getTrackName(track) {
	const simpleText = track?.name?.simpleText;
	const runs = track?.name?.runs
		?.map(run => run?.text)
		?.filter(Boolean)
		?.join("");
	return [simpleText, runs].filter(Boolean).join(" ");
}

function isStrongAutoGeneratedTrack(track) {
	const kind = String(track?.kind ?? getBaseUrlParameter(track?.baseUrl, "kind") ?? "").toLowerCase();
	const vssId = String(track?.vssId ?? "");
	const name = getTrackName(track);
	return kind === "asr" || /^a[._-]/i.test(vssId) || /自动生成|自動生成|auto(?:matically)?[\s-]?generated/i.test(name);
}

function findAutoGeneratedTrackIndex(captionTracks) {
	const strongIndex = captionTracks.findIndex(isStrongAutoGeneratedTrack);
	if (strongIndex >= 0) return strongIndex;

	// 某些响应只在 URL 的 caps=asr 中标记自动字幕；仅有一条候选时才采用，
	// 避免把客户端构造出的多条翻译轨误判成源语言。
	const candidates = captionTracks.map((track, index) => ({ index, caps: String(getBaseUrlParameter(track?.baseUrl, "caps") ?? "").toLowerCase() })).filter(track => track.caps === "asr");
	return candidates.length === 1 ? candidates[0].index : -1;
}

function findSourceTrackIndex(captionTracks, sourceLanguage) {
	const normalizedSource = normalizeLanguage(sourceLanguage);
	if (!normalizedSource || normalizedSource === "auto") return findAutoGeneratedTrackIndex(captionTracks);

	const exactIndex = captionTracks.findIndex(track => normalizeLanguage(getTrackLanguage(track)) === normalizedSource);
	if (exactIndex >= 0) return exactIndex;

	const primaryLanguage = normalizedSource.split("-")[0];
	return captionTracks.findIndex(track => normalizeLanguage(getTrackLanguage(track)).split("-")[0] === primaryLanguage);
}

function setDefaultCaptionTrack(audioTrack, preferredIndex, captionTrackCount) {
	const availableIndices = Array.isArray(audioTrack.captionTrackIndices) ? audioTrack.captionTrackIndices : [];
	if (preferredIndex >= 0 && (!availableIndices.length || availableIndices.includes(preferredIndex))) {
		audioTrack.defaultCaptionTrackIndex = preferredIndex;
		return;
	}

	const currentIndex = audioTrack.defaultCaptionTrackIndex;
	const hasValidCurrentIndex = Number.isInteger(currentIndex) && currentIndex >= 0 && currentIndex < captionTrackCount && (!availableIndices.length || availableIndices.includes(currentIndex));
	if (!hasValidCurrentIndex && availableIndices.length) audioTrack.defaultCaptionTrackIndex = availableIndices[0];
}

export default function setCaptions(captions, translationLanguages, hostname, sourceLanguage = "AUTO") {
	Console.log("☑️ Set Captions");
	// 有播放器字幕列表渲染器
	if (captions?.playerCaptionsTracklistRenderer) {
		const tracklist = captions.playerCaptionsTracklistRenderer;
		Console.info("Tracklist");
		if (Array.isArray(tracklist.captionTracks)) {
			// 改字幕可用性
			tracklist.captionTracks = tracklist.captionTracks.map(caption => {
				caption.isTranslatable = true;
				return caption;
			});
		}

		const captionTracks = Array.isArray(tracklist.captionTracks) ? tracklist.captionTracks : [];
		const preferredIndex = findSourceTrackIndex(captionTracks, sourceLanguage);
		if (preferredIndex >= 0) Console.info(`源语言字幕索引: ${preferredIndex}`, `语言: ${getTrackLanguage(captionTracks[preferredIndex]) || "未知"}`);
		else Console.warn(`未找到匹配的源语言轨道 (${sourceLanguage})，保留 YouTube 默认字幕轨道`);

		if (Array.isArray(tracklist.audioTracks)) {
			// 改音轨可用性
			tracklist.audioTracks = tracklist.audioTracks.map(audio => {
				audio.visibility = 2; //"ON";
				audio.hasDefaultTrack = true;
				audio.captionsInitialState = 3; //"CAPTIONS_INITIAL_STATE_ON_RECOMMENDED";
				setDefaultCaptionTrack(audio, preferredIndex, captionTracks.length);
				return audio;
			});
		}
		// 增加自动翻译可用语言
		switch (hostname) {
			case "www.youtube.com":
			case "tv.youtube.com":
			default:
				tracklist.translationLanguages = translationLanguages.DESKTOP;
				break;
			case "m.youtube.com":
			case "youtubei.googleapis.com":
				tracklist.translationLanguages = translationLanguages.MOBILE;
				break;
		}
	}
	Console.log("✅ Set Captions");
	return captions;
}
