import { Console } from "@nsnanocat/util";

function getBaseUrlParameter(baseUrl, key) {
	if (!baseUrl) return undefined;
	try {
		return new URL(baseUrl).searchParams.get(key) ?? undefined;
	} catch {
		const match = String(baseUrl).match(new RegExp(`[?&]${key}=([^&]+)`, "i"));
		if (!match?.[1]) return undefined;
		try {
			return decodeURIComponent(match[1]);
		} catch {
			return match[1];
		}
	}
}

function getTrackName(track) {
	const simpleText = track?.name?.simpleText;
	const runs = track?.name?.runs
		?.map(run => run?.text)
		?.filter(Boolean)
		?.join("");
	return [simpleText, runs].filter(Boolean).join(" ");
}

function getTrackLanguage(track) {
	return track?.languageCode ?? getBaseUrlParameter(track?.baseUrl, "lang") ?? "";
}

function normalizeLanguage(language) {
	return String(language ?? "")
		.trim()
		.toLowerCase()
		.replaceAll("_", "-");
}

function isAutoGeneratedTrack(track) {
	const kind = String(track?.kind ?? getBaseUrlParameter(track?.baseUrl, "kind") ?? "").toLowerCase();
	const vssId = String(track?.vssId ?? "");
	const name = getTrackName(track);
	return kind === "asr" || /^a[._-]/i.test(vssId) || /自动生成|自動生成|auto(?:matically)?[\s-]?generated/i.test(name);
}

function findLanguageTrackIndex(captionTracks, sourceLanguage) {
	const normalizedSource = normalizeLanguage(sourceLanguage);
	if (!normalizedSource || normalizedSource === "auto") return captionTracks.findIndex(isAutoGeneratedTrack);

	const exactIndex = captionTracks.findIndex(track => normalizeLanguage(getTrackLanguage(track)) === normalizedSource);
	if (exactIndex !== -1) return exactIndex;

	const primaryLanguage = normalizedSource.split("-")[0];
	return captionTracks.findIndex(track => normalizeLanguage(getTrackLanguage(track)).split("-")[0] === primaryLanguage);
}

export default function setCaptions(captions, translationLanguages, hostname, sourceLanguage = "AUTO") {
	Console.log("☑️ Set Captions");
	// 有播放器字幕列表渲染器
	if (captions?.playerCaptionsTracklistRenderer) {
		const tracklist = captions.playerCaptionsTracklistRenderer;
		Console.info("Tracklist");
		if (Array.isArray(tracklist.captionTracks)) {
			// 改字幕可用性
			tracklist.captionTracks = tracklist.captionTracks.map(caption => {
				caption.isTranslatable = true;
				return caption;
			});
		}
		if (Array.isArray(tracklist.audioTracks)) {
			// 改音轨可用性
			tracklist.audioTracks = tracklist.audioTracks.map(audio => {
				audio.visibility = 2; // "ON"
				audio.hasDefaultTrack = true;
				audio.captionsInitialState = 3; // "CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"
				return audio;
			});
		}
		// 增加自动翻译可用语言
		switch (hostname) {
			case "www.youtube.com":
			case "tv.youtube.com":
			default:
				tracklist.translationLanguages = translationLanguages.DESKTOP;
				break;
			case "m.youtube.com":
			case "youtubei.googleapis.com":
				tracklist.translationLanguages = translationLanguages.MOBILE;
				break;
		}

		// 根据轨道元数据选择源语言，不能假设第 0 条轨道就是视频原语言。
		const captionTracks = Array.isArray(tracklist.captionTracks) ? tracklist.captionTracks : [];
		if (captionTracks.length) {
			const preferredIndex = findLanguageTrackIndex(captionTracks, sourceLanguage);
			const currentIndex = Number(tracklist.defaultCaptionTrackIndex);
			const hasValidCurrentIndex = Number.isInteger(currentIndex) && currentIndex >= 0 && currentIndex < captionTracks.length;

			if (preferredIndex >= 0) {
				tracklist.defaultCaptionTrackIndex = preferredIndex;
				Console.info(`源语言字幕索引: ${preferredIndex}`, `语言: ${getTrackLanguage(captionTracks[preferredIndex]) || "未知"}`);
			} else if (!hasValidCurrentIndex) {
				tracklist.defaultCaptionTrackIndex = 0;
				Console.warn(`未找到匹配的源语言轨道 (${sourceLanguage})，回退到第 0 条字幕轨道`);
			}
		}
	}
	Console.log("✅ Set Captions");
	return captions;
}
