import { Console } from "@nsnanocat/util";
import { isSamePrimaryLanguage, normalizeLanguage } from "./language.mjs";

function getBaseUrlParameter(baseUrl, key) {
	if (!baseUrl) return undefined;
	try {
		return new URL(baseUrl).searchParams.get(key) ?? undefined;
	} catch {
		const match = String(baseUrl).match(new RegExp(`[?&]${key}=([^&]+)`, "i"));
		if (!match?.[1]) return undefined;
		try {
			return decodeURIComponent(match[1]);
		} catch {
			return match[1];
		}
	}
}

function getTrackLanguage(track) {
	return track?.languageCode ?? getBaseUrlParameter(track?.baseUrl, "lang") ?? "";
}

function setBaseUrlParameter(baseUrl, key, value) {
	if (!baseUrl) return baseUrl;
	try {
		const url = new URL(baseUrl);
		url.searchParams.set(key, value);
		return url.toString();
	} catch {
		const separator = String(baseUrl).includes("?") ? "&" : "?";
		return `${baseUrl}${separator}${encodeURIComponent(key)}=${encodeURIComponent(value)}`;
	}
}

function getTrackName(track) {
	const simpleText = track?.name?.simpleText;
	const runs = track?.name?.runs
		?.map(run => run?.text)
		?.filter(Boolean)
		?.join("");
	return [simpleText, runs].filter(Boolean).join(" ");
}

function isStrongAutoGeneratedTrack(track) {
	const kind = String(track?.kind ?? getBaseUrlParameter(track?.baseUrl, "kind") ?? "").toLowerCase();
	const vssId = String(track?.vssId ?? "");
	const name = getTrackName(track);
	return kind === "asr" || /^a[._-]/i.test(vssId) || /自动生成|自動生成|auto(?:matically)?[\s-]?generated/i.test(name);
}

function findAutoGeneratedTrackIndex(captionTracks) {
	const strongIndex = captionTracks.findIndex(isStrongAutoGeneratedTrack);
	if (strongIndex >= 0) return strongIndex;

	// 某些响应只在 URL 的 caps=asr 中标记自动字幕；仅有一条候选时才采用，
	// 避免把客户端构造出的多条翻译轨误判成源语言。
	const candidates = captionTracks.map((track, index) => ({ index, caps: String(getBaseUrlParameter(track?.baseUrl, "caps") ?? "").toLowerCase() })).filter(track => track.caps === "asr");
	return candidates.length === 1 ? candidates[0].index : -1;
}

function findSourceTrackIndex(captionTracks, sourceLanguage) {
	const normalizedSource = normalizeLanguage(sourceLanguage);
	if (!normalizedSource || normalizedSource === "auto") return findAutoGeneratedTrackIndex(captionTracks);

	const exactIndex = captionTracks.findIndex(track => normalizeLanguage(getTrackLanguage(track)) === normalizedSource);
	if (exactIndex >= 0) return exactIndex;

	const primaryLanguage = normalizedSource.split("-")[0];
	return captionTracks.findIndex(track => normalizeLanguage(getTrackLanguage(track)).split("-")[0] === primaryLanguage);
}

function findTranslatedTrackIndex(captionTracks, targetLanguage) {
	const normalizedTarget = normalizeLanguage(targetLanguage);
	return captionTracks.findIndex(track => normalizeLanguage(getBaseUrlParameter(track?.baseUrl, "tlang")) === normalizedTarget);
}

function createTranslatedTrack(sourceTrack, targetLanguage, availableTranslationLanguages) {
	const translationLanguage = availableTranslationLanguages.find(language => normalizeLanguage(language?.languageCode) === normalizeLanguage(targetLanguage));
	return {
		baseUrl: setBaseUrlParameter(sourceTrack?.baseUrl, "tlang", targetLanguage),
		name: translationLanguage?.languageName ?? { runs: [{ text: targetLanguage }] },
		vssId: `.${targetLanguage}`,
		languageCode: targetLanguage,
		isTranslatable: false,
	};
}

function setDefaultCaptionTrack(audioTrack, preferredIndex, captionTrackCount) {
	const availableIndices = Array.isArray(audioTrack.captionTrackIndices) ? audioTrack.captionTrackIndices : [];
	if (preferredIndex >= 0 && (!availableIndices.length || availableIndices.includes(preferredIndex))) {
		audioTrack.defaultCaptionTrackIndex = preferredIndex;
		return;
	}

	const currentIndex = audioTrack.defaultCaptionTrackIndex;
	const hasValidCurrentIndex = Number.isInteger(currentIndex) && currentIndex >= 0 && currentIndex < captionTrackCount && (!availableIndices.length || availableIndices.includes(currentIndex));
	if (!hasValidCurrentIndex && availableIndices.length) audioTrack.defaultCaptionTrackIndex = availableIndices[0];
}

export default function setCaptions(captions, translationLanguages, hostname, sourceLanguage = "AUTO", targetLanguage = undefined) {
	Console.log("☑️ Set Captions");
	// 有播放器字幕列表渲染器
	if (captions?.playerCaptionsTracklistRenderer) {
		const tracklist = captions.playerCaptionsTracklistRenderer;
		Console.info("Tracklist");
		if (Array.isArray(tracklist.captionTracks)) {
			// 改字幕可用性
			tracklist.captionTracks = tracklist.captionTracks.map(caption => {
				caption.isTranslatable = true;
				return caption;
			});
		}

		const availableTranslationLanguages = hostname === "m.youtube.com" || hostname === "youtubei.googleapis.com" ? translationLanguages.MOBILE : translationLanguages.DESKTOP;
		const captionTracks = Array.isArray(tracklist.captionTracks) ? tracklist.captionTracks : [];
		const sourceIndex = findSourceTrackIndex(captionTracks, sourceLanguage);
		let preferredIndex = sourceIndex;
		if (sourceIndex >= 0) Console.info(`源语言字幕索引: ${sourceIndex}`, `语言: ${getTrackLanguage(captionTracks[sourceIndex]) || "未知"}`);
		else Console.warn(`未找到匹配的源语言轨道 (${sourceLanguage})，保留 YouTube 默认字幕轨道`);

		if (sourceIndex >= 0 && targetLanguage && !isSamePrimaryLanguage(getTrackLanguage(captionTracks[sourceIndex]), targetLanguage)) {
			preferredIndex = findTranslatedTrackIndex(captionTracks, targetLanguage);
			if (preferredIndex < 0) {
				captionTracks.push(createTranslatedTrack(captionTracks[sourceIndex], targetLanguage, availableTranslationLanguages));
				preferredIndex = captionTracks.length - 1;
			}
			Console.info(`自动翻译字幕索引: ${preferredIndex}`, `语言: ${targetLanguage}`);
		}

		if (Array.isArray(tracklist.audioTracks)) {
			// 改音轨可用性
			tracklist.audioTracks = tracklist.audioTracks.map(audio => {
				audio.visibility = 2; //"ON";
				audio.hasDefaultTrack = true;
				audio.captionsInitialState = 3; //"CAPTIONS_INITIAL_STATE_ON_RECOMMENDED";
				if (preferredIndex >= 0 && Array.isArray(audio.captionTrackIndices) && !audio.captionTrackIndices.includes(preferredIndex)) audio.captionTrackIndices.push(preferredIndex);
				setDefaultCaptionTrack(audio, preferredIndex, captionTracks.length);
				return audio;
			});
		}
		// 增加自动翻译可用语言
		tracklist.translationLanguages = availableTranslationLanguages;
	}
	Console.log("✅ Set Captions");
	return captions;
}
